# Generated by Django 5.2.3 on 2025-12-31 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('localisation', models.CharField(blank=True, max_length=255, null=True)),
                ('categorie', models.CharField(choices=[('eau', 'Eau potable'), ('route', 'Voirie / Routes'), ('eclairage', 'Éclairage public'), ('sante', 'Santé'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('image', models.ImageField(blank=True, default='signalements/signal.jpg', null=True, upload_to='signalements/')),
                ('statut', models.CharField(choices=[('non_traite', 'Non traité'), ('en_cours', 'En cours'), ('traite', 'Traité')], default='non_traite', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('approuver', models.BooleanField(default=False)),
                ('ministere', models.ForeignKey(default=1, limit_choices_to={'is_ministere': True}, on_delete=django.db.models.deletion.CASCADE, related_name='signalements_assignes', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_crees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
