# Generated by Django 6.0.3 on 2026-09-16 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalement', '0001_initial'),
        ('users', '0002_add_is_approved_ministere_fk_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalement',
            name='est_public',
            field=models.BooleanField(default=True, help_text='Si False, seul le citoyen et les agents du ministère pourront voir les médias.'),
        ),
        migrations.AddField(
            model_name='signalement',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Indique si un flux vidéo en direct est en cours.'),
        ),
        migrations.AddField(
            model_name='signalement',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='signalement',
            name='live_room_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signalement',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='signalement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='signalements/audios/'),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='categorie',
            field=models.CharField(choices=[('eau', 'Eau potable'), ('route', 'Voirie / Routes'), ('eclairage', 'Éclairage public'), ('sante', 'Santé'), ('securite', 'Sécurité publique'), ('autre', 'Autre')], default='autre', max_length=50),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='signalements/images/'),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='localisation',
            field=models.CharField(blank=True, help_text='Adresse textuelle', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='ministere',
            field=models.ForeignKey(blank=True, help_text='Le ministère en charge de la résolution.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_assignes', to='users.ministere'),
        ),
    ]
