# Generated by Django 6.0.3 on 2026-09-19 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalement', '0002_signalement_est_public_signalement_is_live_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalement',
            name='live_started_at',
            field=models.DateTimeField(blank=True, help_text='Horodatage du début du live.', null=True),
        ),
        migrations.CreateModel(
            name='LiveFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='signalements/live_frames/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_frames', to='signalement.signalement')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
