# Generated by Django 5.2.3 on 2026-09-16 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ministere',
            options={'verbose_name': 'Ministère', 'verbose_name_plural': 'Ministères'},
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Les comptes citoyens sont approuvés automatiquement. Les comptes autorité/ministère nécessitent une validation admin.'),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='ministere',
            field=models.ForeignKey(blank=True, help_text='Ministère de rattachement (uniquement pour les agents ministériels)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='users.ministere'),
        ),
    ]
