# Generated by Django 6.0.3 on 2026-09-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voixdupeuple',
            name='objectif_votes',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
